name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build and Push Backend Image
        run: |
          docker buildx build -t ${{ secrets.DH_USERNAME }}/backend:latest ./backend --push

      - name: Build and Push Frontend Image
        run: |
          docker buildx build -t ${{ secrets.DH_USERNAME }}/frontend:latest ./frontend --push

      - name: Build and Push Python Service Image
        run: |
          docker buildx build -t ${{ secrets.DH_USERNAME }}/python-service:latest ./py_service --push


  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps: 
      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mediator-image:latest
      - name: Delete old container
        run: docker rm -f mediator-image-container
      - name: Run Docker Container
        run: docker-compose -f docker-compose.yml up -d
