name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mediator-image:latest .
      - name: Publish Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mediator-image:latest
  
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps: 
      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mediator-image:latest
      - name: Delete old container
        run: docker rm -f mediator-image-container
      - name: Run Docker Container
        run: docker-compose -f docker-compose.yml up -d
