name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build Backend Image
        run: docker build -t variatsmol/backend:latest ./backend
      - name: Push Backend Image
        run: docker push variatsmol/backend:latest 

      - name: Build Frontend Image
        run: docker build -t variatsmol/frontend:latest ./frontend
      - name: Push Frontend Image
        run: docker push variatsmol/frontend:latest 

      - name: Build Python service Image
        run: docker build -t variatsmol/py_service:latest ./py_service
      - name: Push Python service Image
        run: docker push variatsmol/py_service:latest 
