name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker Hub
        run: docker login -u ${{secrets.DH_USERNAME}} -p ${{secrets.DH_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mediator-image:latest .
      - name: Publish Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mediator-image:latest
  
  deploy:
    needs: build




    
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-mern-app:latest
            docker stop my-mern-app || true
            docker rm my-mern-app || true
            docker run -d --name my-mern-app -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-mern-app:latest
